DROP TABLE ORDERPROD;
DROP TABLE ORDERS;
DROP TABLE CUSTOMER;
DROP TABLE PRODUCT;

CREATE TABLE PRODUCT
(PRODNO CHAR(4),
PRODDESC VARCHAR(20),
ONHAND INTEGER,
PRODCAT CHAR(6) CHECK (PRODCAT IN ('BBALL', 'HCKY', 'FTBALL', 'SCCR', 'TNNS')),
UNITPRICE DECIMAL(6,2),
PRIMARY KEY (PRODNO)
);

CREATE TABLE
(CUSTNO CHAR(3),
FNAME VARCHAR(25) NOT NULL,
LNAME VARCHAR(25) NOT NULL,
CUSTSTREET VARCHAR(30) NOT NULL,
CUSTCITY VARCHAR(15) NOT NULL,
CUSTPROV VARCHAR(3) NOT NULL,
CUSTPCODE VARCHAR(6) NOT NULL,
PRIMARY KEY (CUSTNO)
);

CREATE TABLE ORDERS
(ORDERNO CHAR(5) UNIQUE NOT NULL,
ORDERDATE DATE,
CUSTNO CHAR(3) NOT NULL,
FOREIGN KEY (CUSTNO) REFERENCES CUSTOMER (CUSTNO)
);

CREATE TABLE ORDERPROD
(ORDERNO CHAR(5),
PRODNO CHAR(4),
ORDERQTY INTEGER CHECK (ORDERQTY>0),
ORDERPRICE DECIMAL(7,2),
PRIMARY KEY (ORDERNO, PRODNO),
FOREIGN KEY (ORDERNO) REFERENCES ORDERS(ORDERNO),
FOREIGN KEY (PRODNO) REFERENCES PRODUCT(PRODNO)
);

CREATE OR REPLACE VIEW CART AS
SELECT DISTINCT C.CUSTNO, P.PRODNO, PRODDESC, ORDERQTY, SUM(ORDERQTY * ORDERPRICE) AS 'SUB TOTAL'
FROM CUSTOMER C, ORDERPROD OP, PRODUCT P, ORDERS O
WHERE P.PRODNO = OP.PRODNO
AND OP.ORDERNO = O.ORDERNO
AND O.CUSTNO = C.CUSTNO;

INSERT INTO PRODUCT
   VALUES
      ('0001', 'TML AUTH HOME JERSEY', 100, 'HCKY', 329.99);