DROP TABLE ORDERPROD;
DROP TABLE ORDERS;
DROP TABLE PRODUCT;

CREATE TABLE PRODUCT
(PRODNO CHAR(4),
PRODDESC VARCHAR(20),
ONHAND INTEGER,
PRODCAT CHAR(6) CHECK (PRODCAT IN ('BBALL', 'HCKY', 'FTBALL', 'SCCR', 'TNNS')),
UNITPRICE DECIMAL(6,2),
PRIMARY KEY (PRODNO)
);

CREATE TABLE ORDERS
(ORDERNO INT(5) UNIQUE NOT NULL,
ORDERDATE DATE,
ID INT(5) NOT NULL,
FOREIGN KEY (ID) REFERENCES USERS (ID)
);

CREATE TABLE ORDERPROD
(ORDERNO INT(5),
PRODNO CHAR(4),
ORDERQTY INTEGER CHECK (ORDERQTY>0),
ORDERPRICE DECIMAL(7,2),
PRIMARY KEY (ORDERNO, PRODNO),
FOREIGN KEY (ORDERNO) REFERENCES ORDERS(ORDERNO),
FOREIGN KEY (PRODNO) REFERENCES PRODUCT(PRODNO)
);

CREATE OR REPLACE VIEW CART AS
SELECT U.ID, O.ORDERNO, P.PRODNO, PRODDESC, ORDERQTY, (ORDERQTY * ORDERPRICE) AS 'SUBTOTAL'
FROM USERS U, ORDERPROD OP, PRODUCT P, ORDERS O
WHERE P.PRODNO = OP.PRODNO
AND OP.ORDERNO = O.ORDERNO
AND O.ID = U.ID;

INSERT INTO PRODUCT
   VALUES
      ('0001', 'TML AUTH HOME JERSEY', 100, 'HCKY', 329.99);

INSERT INTO ORDERS
   VALUES
      (10001, '2011-12-06', 2);

INSERT INTO ORDERPROD
   VALUES
      (10001, '0001', 5, (SELECT UNITPRICE FROM PRODUCT WHERE PRODNO = 0001));